[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.2"

# Enable form detection
[build.processing]
  skip_processing = false

# Form settings
[[headers]]
  for = "/netlify-form.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
